#pragma once

#define SQUARE_LENGTH 125
#define SEPARATION 25
#define END_WIDTH 50
#define END_HEIGHT 425
#define PRICE_SIZE 20
#define HEART_SIZE 100
#define SHOOTER_SIZE 9
#define PRICE_SEPARATION 40
#define NR_SHOOTERS 4