#pragma once

#define SQUARE_LENGTH 125
#define SEPARATION 20
#define END_WIDTH 50
#define END_HEIGHT 3 * SQUARE_LENGTH + 2 * SEPARATION
#define PRICE_SIZE SQUARE_LENGTH / 3
#define ENEMY_SIZE 100
#define PROJECTILE_SIZE 100
#define HEART_SIZE 100
#define SHOOTER_SIZE 9
#define PRICE_SEPARATION PRICE_SIZE
#define NR_SHOOTERS 4
#define ACCELERATION 1.25f
#define START_SPEED 0.5f
#define PROJECTILE_SPEED 400
#define PROJECTILE_ROTATION 5
#define PROJECTILE_LAUNCH_INTERVAL 1500